Fix echo import by a request
vgocoder
10:21

I follow the README.md ，but error. go get -u
github.com/kataras/go-http-routing-benchmark
github.com/kataras/go-http-routing-benchmark

./routers.go:339: c.Response undefined (type echo.Context is pointer to
interface, not interface)
./routers.go:339: c.Param undefined (type echo.Context is pointer to
interface, not interface)
./routers.go:344: c.Response undefined (type echo.Context is pointer to
interface, not interface)
./routers.go:344: c.Request undefined (type echo.Context is pointer to
interface, not interface)
./routers.go:358: cannot use h (type interface {}) as type echo.Handler
in argument to e.Get:
interface {} does not implement echo.Handler (missing Handle method)
./routers.go:360: cannot use h (type interface {}) as type echo.Handler
in argument to e.Post:
interface {} does not implement echo.Handler (missing Handle method)
./routers.go:362: cannot use h (type interface {}) as type echo.Handler
in argument to e.Put:
interface {} does not implement echo.Handler (missing Handle method)
./routers.go:364: cannot use h (type interface {}) as type echo.Handler
in argument to e.Patch:
interface {} does not implement echo.Handler (missing Handle method)
./routers.go:366: cannot use h (type interface {}) as type echo.Handler
in argument to e.Delete:
interface {} does not implement echo.Handler (missing Handle method)
./routers.go:371: cannot use e (type echo.Echo) as type http.Handler in
return argument: echo.Echo does not implement http.Handler (wrong type
for ServeHTTP method)
have ServeHTTP(engine.Request, engine.Response)
want ServeHTTP(http.ResponseWriter, *http.Request)
./routers.go:371: too many errors
@kataras Can U help me ?

vgocoder
11:54
I just replace "github.com/labstack/echo"
with "gopkg.in/labstack/echo.v1” in file “routers.go” line 36
and “go get gopkg.in/gopkg.in/labstack/echo.v1”
It works